name: eden_xi_tools_api
description: A dart api client that for the Final Fantasy XI Eden private server tools.
version: 1.0.2
homepage: https://github.com/wardy484/eden_xi_dart_api

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.4
  json_serializable: ^6.3.0
  lints: ^2.0.0
  test: ^1.16.0
